version: '3.8'

services:

  db:
    image: postgres:13
    container_name: hord-db
    command: ["postgres", "-N", "1024", "-c", "shared_buffers=4GB"]
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HASURA_METADATA_DB: ${HASURA_METADATA_DB}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
    - ./.local/db:/docker-entrypoint-initdb.d
    - data:/var/lib/postgresql/data

  hord-ctl:
    image: vbogretsov/hord-ctl:0.1.0
    build:
      context: .
    restart: on-failure
    container_name: hord-ctl
    hostname: hord-ctl
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${HASURA_GRAPHQL_METADATA_DATABASE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HORD_SECRET_KEY}
      HASURA_GRAPHQL_ENDPOINT: http://web
    depends_on:
    - db

  hord-1:
    image: hasura/graphql-engine:v2.0.7
    restart: always
    container_name: hord-1
    hostname: hord-1
    entrypoint: ["graphql-engine"]
    command: ["serve"]
    ports:
    - 8080:8080
    environment:
    - HASURA_GRAPHQL_DATABASE_URL=${HASURA_GRAPHQL_DATABASE_URL}
    - HASURA_GRAPHQL_METADATA_DATABASE_URL=${HASURA_GRAPHQL_METADATA_DATABASE_URL}
    - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    - HASURA_GRAPHQL_ADMIN_SECRET=${HORD_SECRET_KEY}
    - HASURA_GRAPHQL_PG_STRIPES=1
    - HASURA_GRAPHQL_PG_CONNECTIONS=512
    - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET}
    depends_on:
    - db

  hord-2:
    image: hasura/graphql-engine:v2.0.7
    restart: always
    container_name: hord-2
    hostname: hord-2
    entrypoint: ["graphql-engine"]
    command: ["serve"]
    ports:
    - 8081:8080
    environment:
    - HASURA_GRAPHQL_DATABASE_URL=${HASURA_GRAPHQL_DATABASE_URL}
    - HASURA_GRAPHQL_METADATA_DATABASE_URL=${HASURA_GRAPHQL_METADATA_DATABASE_URL}
    - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    - HASURA_GRAPHQL_ADMIN_SECRET=${HORD_SECRET_KEY}
    - HASURA_GRAPHQL_PG_STRIPES=1
    - HASURA_GRAPHQL_PG_CONNECTIONS=512
    - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET}
    depends_on:
    - db

  web:
    image: nginx
    restart: always
    container_name: web
    hostname: web
    volumes:
    - ./.local/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 80:80
    environment:
    - NGINX_PORT=80
    depends_on:
    - hord-1
    - hord-2

  hord:
    image: hasura/graphql-engine:v2.0.7.cli-migrations-v3
    restart: always
    container_name: hord
    hostname: hord
    ports:
    - 8000:8080
    environment:
    - HASURA_GRAPHQL_DATABASE_URL=${HASURA_GRAPHQL_DATABASE_URL}
    - HASURA_GRAPHQL_METADATA_DATABASE_URL=${HASURA_GRAPHQL_METADATA_DATABASE_URL}
    - HASURA_GRAPHQL_ENABLE_CONSOLE=false
    - HASURA_GRAPHQL_ADMIN_SECRET=${HORD_SECRET_KEY}
    - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET}
    volumes:
    - ./migrations:/hasura-migrations
    - ./metadata:/hasura-metadata
    depends_on:
    - db

  tests:
    build: ./tests
    container_name: tests
    ports:
    - 5900:5900
    depends_on:
    - hord
    environment:
    - HASURA_GRAPHQL_ADMIN_SECRET=${HORD_SECRET_KEY}
    - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET}
    volumes:
    - ./tests/features:/src/test/java

volumes:
  data: {}
