version: '3.8'

services:

  db:
    image: hord-db
    build: db
    container_name: hord-db
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - HASURA_METADATA_DB=${HASURA_METADATA_DB}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}

  hord-ctl:
    image: hord-ctl
    build: .
    restart: on-failure
    container_name: hord-ctl
    environment:
    - HASURA_GRAPHQL_DATABASE_URL=${HASURA_GRAPHQL_DATABASE_URL}
    - HASURA_GRAPHQL_METADATA_DATABASE_URL=${HASURA_GRAPHQL_METADATA_DATABASE_URL}
    - HASURA_GRAPHQL_ENABLE_CONSOLE=false
    - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
    - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET}
    - HASURA_GRAPHQL_ENDPOINT=http://hord-app:8080
    depends_on:
    - db

  hord-app:
    image: hasura/graphql-engine:v2.0.7
    restart: on-failure
    container_name: hord-app
    ports:
    - 8080:8080
    environment:
    - HASURA_GRAPHQL_DATABASE_URL=${HASURA_GRAPHQL_DATABASE_URL}
    - HASURA_GRAPHQL_METADATA_DATABASE_URL=${HASURA_GRAPHQL_METADATA_DATABASE_URL}
    - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
    - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET}
    depends_on:
    - hord-ctl
