version: '3.8'

services:

  db:
    image: postgres:13
    container_name: hord-db
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - HASURA_METADATA_DB=${HASURA_METADATA_DB}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    volumes:
    - ./.local/db:/docker-entrypoint-initdb.d
    - data:/var/lib/postgresql/data

  hord:
    image: hasura/graphql-engine:v2.0.7.cli-migrations-v3
    restart: always
    container_name: hord
    hostname: hord
    ports:
    - 8080:8080
    environment:
    - HASURA_GRAPHQL_DATABASE_URL=${HASURA_GRAPHQL_DATABASE_URL}
    - HASURA_GRAPHQL_METADATA_DATABASE_URL=${HASURA_GRAPHQL_METADATA_DATABASE_URL}
    - HASURA_GRAPHQL_ENABLE_CONSOLE=false
    - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
    - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET}
    volumes:
    - ./migrations:/hasura-migrations
    - ./metadata:/hasura-metadata
    depends_on:
    - db

  tests:
    image: tests
    build: tests
    container_name: hord-tests
    environment:
    - TEST_DSN=${HASURA_GRAPHQL_DATABASE_URL}
    - TEST_URL=http://hord:8080
    - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET}
    volumes:
    - ./tests:/src
    depends_on:
    - hord

volumes:
  data: {}
