name: Tests

on:
  pull_request:
    branches:
    - "*"
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      HASURA_METADATA_DB: hasura
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DB_NAME: hord
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      HASURA_GRAPHQL_DATABASE_URL: postgres://${{ secrets.DB_NAME }}:${{ secrets.DB_PASS }}@db/hord?sslmode=disable
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${{ secrets.DB_NAME }}:${{ secrets.DB_PASS }}@db/hasura?sslmode=disable
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
      HASURA_GRAPHQL_JWT_SECRET: ${{ secrets.HASURA_GRAPHQL_JWT_SECRET }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker-compose build
    - name: Run Containers
      run: docker-compose up -d
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Test Dependencies
      run: python -m pip install -r tests/requirements.txt
    - name: Run Tests
      run: pytest -v
      env:
        TEST_URL: http://localhost:8080
        TEST_DSN: postgres://${{ secrets.DB_NAME }}:${{ secrets.DB_PASS }}@localhost/hord?sslmode=disable
