name: Tests

on:
  pull_request:
    branches:
    - "*"
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      HASURA_GRAPHQL_JWT_SECRET: ${{ secrets.HASURA_GRAPHQL_JWT_SECRET }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Services
      run: docker-compose up -d --build
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        HASURA_METADATA_DB: hasura
        DB_NAME: hord
        DB_USER: hord
        DB_PASS: ${{ secrets.DB_PASS }}
        HASURA_GRAPHQL_DATABASE_URL: postgres://hord:${{ secrets.DB_PASS }}@db/hord?sslmode=disable
        HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://hord:${{ secrets.DB_PASS }}@db/hasura?sslmode=disable
        HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
        HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
        HASURA_GRAPHQL_ENDPOINT: http://hord-app:8080
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: pip install -r tests/requirements.txt
    - name: Run Tests
      run: pytest
      env:
        TEST_DSN: postgres://hord:${{ secrets.DB_PASS }}@localhost/hord?sslmode=disable
        TEST_URL: http://localhost:8080

